# Generated by Django 3.0.3 on 2020-02-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=45)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=45)),
                ('horsepower', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('car_make_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dj_cars.Make')),
            ],
        ),
    ]
