# Generated by Django 3.0.3 on 2020-02-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='car_make',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
